---
- name: backup tamlab.brq.db
  copy:
    src: "{{ tamlab_brq_db_path }}"
    dest: "{{ tamlab_brq_db_path }}_bak"
    remote_src: yes

- name: Copy ocp record to tamlab dns server /var/named
  template: 
    src: ocp_dns.j2
    dest: "{{ conf_path }}"
    mode: 0644
  become: yes
 

- name: Add the conf file to /var/named/tamlab.brq.db
  lineinfile:
    path: "{{ tamlab_brq_db_path }}"
    regexp: "^$INCLUDE {{ user_name }}_ocp.conf"
    line: "$INCLUDE ./{{ user_name }}_ocp.conf"
  become: yes

- name: named service is reloaded
  systemd: state=reloaded name=named
  become: yes

