---
- name: Copy ocp record to tamlab dns server /var/named
  file: 
    path: "{{ conf_path }}"
    state: absent
    remote_src: yes


- name: Add the conf file to /var/named/tamlab.brq.db
  lineinfile:
    path: "{{ tamlab_brq_db_path }}"
    regexp: "{{ user_name }}_ocp.conf"
    line: ""
    state: absent

- name: named service is reloaded
  systemd: state=reloaded name=named
