---

#- name: Get public key content
#  shell: "cat {{ ssh_key }}"
#  register: ssh_public_key
#
#- name: Add public key to TAMlab dns server
#  lineinfile: 
#    path: "/{{ tamlab_dns_server_user }}/.ssh/authorized_keys"
#    line: "{{ ssh_public_key.stdout }}"

- name: Add dns records
  import_tasks: ./create.yaml
  when: op == 'create'

- name: Delete dns records
  import_tasks: ./delete.yaml
  when: op == 'delete'
