---
- name: Check if instance exist
  os_server_facts:
    cloud: "{{ os_project }}"
    server: "{{ instance_name }}"

- name: Create static port allocations if an instance does not exist
  os_port:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ instance_name }}"
     network: "{{ network_name }}"
  when: openstack_servers|length == 0
     
- name: Create OpenShift an instance if it does not exist
  os_server:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ instance_name }}"
     image: "{{ instance_image }}"
     key_name: "{{ user_name }}"
     flavor: "{{ instance_flavor }}"
     security_groups: "{{ security_grp_name }}"
     wait: yes
     timeout: 300
     nics:
       - port-name: "{{ instance_name }}"
     auto_ip: yes
  register: new_server
  when: openstack_servers|length == 0

- name: Gather instance information
  os_server_facts:
    cloud: "{{ os_project }}"
    server: "{{ instance_name }}"
  when: openstack_servers|length == 0
  register: created_instance

- import_tasks: ./add_hosts.yaml

- debug: "msg={{groups['masters']}}"
- name: Add floating ip for the first master node
  os_floating_ip:
     cloud: "{{ os_project }}"
     state: present
     reuse: yes
     server: "{{ instance_name }}"
     network: "{{ external_network_name }}"
     wait: true
     timeout: 180
  when: 
  - "groups['masters']|length == 1"
  - created_instance is not skipped
 
