---
- name: Register node to rhsm and attach pool using subscription username/password
  redhat_subscription:
    username: "{{ subs_id }}"
    password: "{{ subs_pw }}"
    pool: "^{{ pool_name }}$"
    state: present
    force_register: yes
  when: 
  - subs_id is defined and subs_id != ''
  - subs_pw is defined and subs_pw != ''
  - pool_name is defined
  register: task_result
  until: task_result|success
  retries: 10
  delay: 1
  ignore_errors: yes
  become: yes
  become_user: root

- name: Register node to rhsm and attach pool using activation key
  redhat_subscription:
    activationkey: "{{ act_key }}"
    org_id: "{{ org_id }}"
    pool: "^{{ pool_name }}$"
    state: present
    force_register: yes
  when: 
  - act_key is defined and act_key != ''
  - pool_name is defined
  register: task_result
  until: task_result|success
  retries: 10
  delay: 1
  ignore_errors: yes
  become: yes
  become_user: root

- name: Register node to rhsm and attach pool using id
  redhat_subscription:
    username: "{{ subs_id }}"
    password: "{{ subs_pw }}"
    pool_ids: "{{ pool_id }}"
    state: present
    force_register: yes
  when: 
  - subs_id is defined and subs_id != ''
  - subs_pw is defined and subs_pw != ''
  - pool_id is defined
  - pool_name is not defined
  register: task_result
  until: task_result|success
  retries: 10
  delay: 1
  ignore_errors: yes
  become: yes
  become_user: root

- debug: var=task_result
