- name: Create project
  os_project:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ user_project }}"
     description: OCP 3.x Project
     domain_id: "{{ user_domain }}"
     enabled: True

- name: Change project quota
  os_quota:
     cloud: "{{ os_admin }}"
     name: "{{ user_project }}"
     cores: "{{ quota_cores }}"
     ram: "{{ quota_ram }}"

- name: Create user
  os_user:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ user_name }}"
     password: "{{ user_pw }}"
     email: "{{ user_email }}"
     domain: "{{ user_domain }}"
     default_project: "{{ user_project }}"

- name: Associate roles
  os_user_role:
     cloud: "{{ os_admin }}"
     user: "{{ user_name }}"
     role: "{{ item }}"
     project: "{{ user_project }}"
  with_items:
  - "{{ user_roles }}"

- name: Add keypair
  os_keypair:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ user_name }}"
     public_key_file: "{{ ssh_key }}"

- name: Create Security Group for OCP3
  os_security_group:
    state: present
    cloud: "{{ os_project }}"
    name: "{{ security_grp_name }}"
    project: "{{ user_project }}"
    description: Security Group for OCP3

- name: Add Security Group Rules
  os_security_group_rule:
     cloud: "{{ os_project }}"
     security_group: "{{ security_grp_name }}"
     project: "{{ user_project }}"
     protocol: "{{ item.protocol }}"
     remote_ip_prefix: "{{ item.remote_ip_prefix }}"
  with_items:
  - "{{ security_grp_rules }}"

- name: Create master vm flavors
  os_nova_flavor:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ item.name }}"
     ram: "{{ item.ram }}"
     vcpus: "{{ item.vcpus }}"
     disk: "0"
     ephemeral: "{{ item.disk }}"
  with_items:
  - "{{ master_flavors }}"

- name: Create node vm flavors
  os_nova_flavor:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ item.name }}"
     ram: "{{ item.ram }}"
     vcpus: "{{ item.vcpus }}"
     disk: "{{ item.disk }}"
  with_items:
  - "{{ node_flavors }}"

- name: Add network
  os_network:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ network_name }}"
     project: "{{ user_project }}"
     shared: no
     external: false

- name: Add subnet to network
  os_subnet:
     state: present
     cloud: "{{ os_project }}"
     project: "{{ user_project }}"
     network_name: "{{ network_name }}"
     name: "{{ osp_subnet.name }}"
     cidr: "{{ osp_subnet.cidr }}"
     gateway_ip: "{{ osp_subnet.cidr | ipaddr('next_usable') }}"
     allocation_pool_start: "{{ osp_subnet.cidr | next_nth_usable(2) }}"
     allocation_pool_end: "{{ osp_subnet.cidr | ipaddr('last_usable') }}"
     ip_version: 4
     dns_nameservers:
        - "{{ intrim_dns_server }}"



- name: Create router for private and external routing
  os_router:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ router_name }}"
     project: "{{ user_project }}"
     network: "{{ external_network_name }}"
     enable_snat: yes
     interfaces:
        - "{{ osp_subnet.name }}"

