need_repo_list:
- rhel-7-server-rpms
- rhel-7-server-ose-3.11-rpms
- rhel-7-server-extras-rpms
- rhel-7-server-ansible-2.6-rpms

install_packages:
- wget
- git
- yum-utils
- net-tools
- bind-utils
- iptables-services 
- bridge-utils 
- bash-completion 
- kexec-tools 
- sos 
- psacct
- openshift-ansible
- atomic-openshift-excluder 
- atomic-openshift-docker-excluder 
- skopeo

openshift_ansible_version: ''
openshift_ansible_pkg_name: openshift-ansible
