---

- name: Delete OpenShift an instance 
  os_server:
     state: absent
     cloud: "{{ os_project }}"
     name: "{{ instance_name }}"
     terminate_volume: yes
     delete_fip: yes
     security_groups:
     -  "{{ security_grp_name }}"
     wait: yes
     timeout: 300
#     meta:
#       hostname: "{{ instance_name }}.{{ dns_domain }}"
#     userdata: |
#       hostname: "{{ instance_name }}.{{ dns_domain }}"
#       fqdn: "{{ instance_name }}.{{ dns_domain }}"

- name: Delete a volume for docker
  os_volume:
     state: absent
     cloud: "{{ os_project }}"
     display_name: "{{ instance_name }}-docker"

- name: Delete static port allocations if an instance does not exist
  os_port:
     state: absent
     cloud: "{{ os_project }}"
     name: "{{ instance_name }}"
     network: "{{ network_name }}"

- name: Delete floating ip for node
  os_floating_ip:
     cloud: "{{ os_project }}"
     state: absent
     reuse: yes
     server: "{{ instance_name }}"
     network: "{{ external_network_name }}"
     wait: true
     timeout: 180
  ignore_errors: yes
  
