---

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable necessary repositories
  rhsm_repository:
    name: "{{ need_repo_list| join(',') }}"


# Ansible 2.8
#- name: Disable all repositories except rhel-7-server-rpms
#  rhsm_repository:
#    name: need_repo_list| join(',')
#    purge: True

