- hosts: masters
  gather_facts: no
  become: yes
  tasks:
  - file:
      path: /etc/ocp_htpasswd
      state: touch

- hosts: masters[0]
  gather_facts: no
  become: yes
  tasks:
#  - name: Check out official openshift ansible github repository
#    git:
#      repo: "https://github.com/openshift/openshift-ansible.git"
#      dest: "/root/openshift-ansible"
#      version: "release-3.11"
#    ignore_errors: yes

  - name: Put ssh private key
    copy: 
      src: "{{ lookup('env','HOME')}}/.ssh/id_rsa"
      dest: "/root/.ssh/id_rsa"
      mode: '0600'

  - name: Put ocp hosts file
    copy: 
      src: "{{ lookup('env','PWD')}}/hosts_{{ user_name }}"
      dest: "/root/hosts"
   
  - name: Put ansible.cfg file
    copy: 
      src: "{{ lookup('env','PWD')}}/ansible.cfg"
      dest: "/etc/ansible/ansible.cfg"
      backup: yes
  
  - name: Execute OCP installation Ansible
    shell: "ansible-playbook -i /root/hosts /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml -vvvv"
