---

- name: Generate haproxy conf for Router members
  template: 
    src: haproxy.j2
    dest: "/tmp/haproxy_{{ user_name }}"

- name: Copy the content of haproxy conf
  shell: "cat /tmp/haproxy_{{ user_name }}"
  register: haproxy_conf

- name: Add Router members to LB haproxy
  lineinfile:
    line: "{{ haproxy_conf.stdout }}"
    regex: '^listen ingress-http$'
    dest: "{{ haproxy_conf_path }}"

- name: Restart haproxy
  systemd:
    state: restarted
    name: haproxy    
